### ISSUE TITLE
Not loading product configurations in WHMCS 8.6 PHP 8.1

### ISSUE THREAD

**Issue by Businezz99** [hivelocity/bare-metal-provisioning-module-for-whmcs#22]
Are there any updates coming in for WHMCS 8.6 with PHP 8.1 and ioncube 12? Server configurations are not loading in **Module Settings** when editing products.

**Comment by bstetler** [comment]
I am putting it on of the the guys board to see what the issues are. If you see any errors that you can share please do. We will get back to you.

Thank you

**Comment by Businezz99** [comment]
> I am putting it on of the the guys board to see what the issues are. If you see any errors that you can share please do. We will get back to you.
> 
> Thank you

There are no errors that are showing, just the available servers are not loading anymore, basically, it does nothing when clicking on Module Settings.

**Comment by bstetler** [comment]
Under System logs -> Module logs Did you enable Module Logging?

**Comment by Businezz99** [comment]
> Under System logs -> Module logs Did you enable Module Logging?

Action:
`hivelocity_configoptions`

Request:
`Array
(
    [whmcsVersion] => 8.6.0-release.1
    [producttype] => server
    [action] => ConfigOptions
)
`

Response:

> #0 /home/MYUSER/public_html/modules/servers/Hivelocity/classes/Helpers.php(22): PDO->commit()
#1 /home/MYUSER/public_html/modules/servers/Hivelocity/classes/Addon.php(10): Hivelocity\classes\Helpers::maintenanceDatabase()
#2 /home/MYUSER/public_html/modules/servers/Hivelocity/Hivelocity.php(19): Hivelocity\classes\Addon::getConfig(Array)
#3 [internal function]: Hivelocity_ConfigOptions(Array)
#4 /home/MYUSER/public_html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('Hivelocity_Conf...', Array)
#5 /home/MYUSER/public_html/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->call('ConfigOptions', Array)
#6 /home/MYUSER/public_html/vendor/whmcs/whmcs-foundation/lib/Admin/Setup/ProductSetup.php(0): WHMCS\Module\Server->call('ConfigOptions', Array)
#7 /home/MYUSER/public_html/vendor/whmcs/whmcs-foundation/lib/Admin/Setup/ProductSetup.php(0): WHMCS\Admin\Setup\ProductSetup->hasSimpleConfigMode()
#8 /home/MYUSER/public_html/vendor/whmcs/whmcs-foundation/lib/Admin/Setup/ProductSetup.php(0): WHMCS\Admin\Setup\ProductSetup->getModuleSetupRequestMode()
#9 /home/MYUSER/public_html/vendor/whmcs/whmcs-foundation/lib/Admin/Setup/ProductSetup.php(0): WHMCS\Admin\Setup\ProductSetup->getModuleSettingsFields()
#10 /home/MYUSER/public_html/MY-ADMIN/configproducts.php(0): WHMCS\Admin\Setup\ProductSetup->getModuleSettings(163, Object(WHMCS\Http\Message\ServerRequest))
#11 {main}

**Comment by Businezz99** [comment]
@bstetler Any updates on the module?

**Comment by Businezz99** [comment]
> Hello
> 
> @Businezz99 Please update using the latest version we have patched the module to work with php 8.1 and ioncube V12

Hey, thanks! It works. The only thing i noticed is when i choose Almalinux 8, control panel field is locked i can't choose cPanel. If i switch to CentOS then i can choose cPanel license. https://snipboard.io/itHPyn.jpg

**Comment by cyber-ninjaX** [comment]
Thanks for confirming we will have the dev team that manages the backend api review that option. Was it on a certain device/product or all products/device with the Almalinux 8 options. I will confirm with them to add all of the supported OS options for cpanel

cPanel currently supports the following operating systems.

 https://docs.cpanel.net/installation-guide/system-requirements/

CentOS 7
CloudLinux 6, 7, and 8
Red Hat Enterprise Linux 7
AlmaLinux 8
Ubuntu 20.04 LTS (on cPanel/WHM version 102 and higher)

**Comment by Businezz99** [comment]
> 

Hey, only Almalinux 8.x and Ubuntu 20.x doesn't allow to choose cPanel. CentOS works fine.

**Comment by cyber-ninjaX** [comment]
new version and steps launched 

https://github.com/hivelocity/bare-metal-provisioning-module-for-whmcs/releases

**Comment by Businezz99** [comment]
@cyber-ninjaX thanks, I’ll take a look.

**Comment by Businezz99** [comment]
@cyber-ninjaX I just updated the module and when i go in Modules > Hivelocity pricing tool i got error.

`Error: Call to undefined function HivelocityPricingTool\classes\shell_exec() in /home/username/public_html/modules/addons/HivelocityPricingTool/classes/Addon.php:68`

**Comment by cyber-ninjaX** [comment]
Please check your php disable function and confirm its not disabled.

Usage example
disable_functions=exec,passthru,shell_exec,system,proc_open,popen

If that is list please remove and try once more.

**Comment by bstetler** [comment]
This issue was resolved. If you have further issues let us know.
